classname: pipelines.{{ cookiecutter.module }}.pipeline.{{ cookiecutter.classname }}

triggers:
  # DEVELOPER: Update regex patterns that should trigger this pipeline
  - .*{{ cookiecutter.location_id}}.*\.csv

retriever:
  path: pipelines/example_ingest/config/retriever.yaml

dataset:
  path: pipelines/example_ingest/config/dataset.yaml

quality:
  path: pipelines/example_ingest/config/quality.yaml

storage:
  path: shared/config/storage.yaml
