# DEVELOPER: Specify the quality checks and handlers that should be applied
managers:
  - name: Custom Quality Check and Corrections
    checker:
      classname: pipelines.{{ cookiecutter.module }}.qc.CustomQualityChecker
      parameters: {}
    handlers:
      - classname: pipelines.{{ cookiecutter.module }}.qc.CustomQualityHandler
        parameters: {}
    apply_to:
      # keyword for coordinate variables (e.g., 'time')
      - COORDS
      # keyword for all other variables
      - DATA_VARS
