# DEVELOPER: Add attrs and coords/variables to specify the output data structure

# TODO: Make sure the data/vars/attrs matches the example dataset
attrs:
  title: title
  description: description
  location_id: abc
  dataset_name: example
  data_level: b1

coords:
  time:
    dims: [time]
    dtype: datetime64[s]
    attrs:
      units: Seconds since 1970-01-01 00:00:00

data_vars:
  example_var:
    dims: [time]
    dtype: float
    attrs:
      units: km

  pi:
    data: 3.14159
    dims: []
    dtype: float
    attrs:
      units: "1"
