attrs:
  title: title
  description: description
  location_id: abc
  dataset_name: example
  data_level: a1

coords:
  time:
    dims: [time]
    dtype: datetime64[s]
    attrs:
      units: Seconds since 1970-01-01 00:00:00

data_vars:
  example_var:
    dims: [time]
    dtype: float
    attrs:
      units: km
