classname: tsdat.pipeline.ingest.IngestPipeline

triggers:
  # DEVELOPER: Update regex patterns that should trigger this pipeline
  - .*example_ingest.*\.csv

retriever:
  path: pipelines/example_ingest/config/retriever.yaml

dataset:
  path: pipelines/example_ingest/config/dataset.yaml

quality:
  # path: shared/config/custom-quality.yaml # COOKIECUTTER
  path: shared/config/default-quality.yaml

storage:
  path: shared/config/storage.yaml
