# DEVELOPER: Add attrs and coords/variables to specify the output data structure

attrs:
  title: {{ cookiecutter.name }}
  description: {{ cookiecutter.description }}
  location_id: {{ cookiecutter.__location_id }}
  dataset_name: {{ cookiecutter.__module }}
  data_level: {% if cookiecutter.use_custom_qc == "no" %}a1{% else %}b1{% endif %}
  # qualifier: 
  # temporal: 
  # institution: 

coords:
  time:
    dims: [time]
    dtype: datetime64[s]
    attrs:
      units: Seconds since 1970-01-01 00:00:00

data_vars:
  example_var:
    dims: [time]
    dtype: float
    attrs:
      long_name:  Example Variable
      units: km
