# DEVELOPER: Specify the quality checks and handlers that should be applied
managers:
  - name: The name of this quality check
    checker:
      classname: pipelines.example_ingest.qc.CustomQualityChecker
      parameters: {}
    handlers:
      - classname: pipelines.example_ingest.qc.CustomQualityHandler
        parameters: {}
    apply_to: [COORDS, DATA_VARS]
